;;;;;;;;;;;;;;;;;;;;;;;;;;
; Database Configuration ;
;;;;;;;;;;;;;;;;;;;;;;;;;;

[database]
host     = "localhost"
username = "DBUSER"
password = "DBPASSWORD"
dbname   = "DBNAME"
prefix   = "omeka_"
charset  = "utf8"
port     = ""
